extends GutTest

## The variant hash ported from the legacy `variation.ts` must match it exactly, or a map authored
## against the old renderer picks different tiles here. The expected values below were generated by
## running the original JS `hash32` with the demo map's seed.

const SEED := 1311768467


func test_hash32_matches_the_reference_vectors() -> void:
	assert_eq(MapVariation.hash32(SEED, 0, 0, 0), 1107709302)
	assert_eq(MapVariation.hash32(SEED, 3, 4, 0), 3226071954)
	assert_eq(MapVariation.hash32(SEED, 10, 7, 1), 3455381140)
	assert_eq(MapVariation.hash32(SEED, 39, 27, 6), 1822162484)
	assert_eq(MapVariation.hash32(SEED, 5, 12, 2048), 936880704)


func test_pick_variant_is_the_hash_modulo_count() -> void:
	# The same vectors reduced mod 4 (the biome variant count).
	assert_eq(MapVariation.pick_variant(SEED, 0, 0, 0, 4), 2)
	assert_eq(MapVariation.pick_variant(SEED, 3, 4, 0, 4), 2)
	assert_eq(MapVariation.pick_variant(SEED, 10, 7, 1, 4), 0)


func test_a_single_or_zero_variant_is_always_index_zero() -> void:
	assert_eq(MapVariation.pick_variant(SEED, 7, 9, 0, 1), 0, "one variant never hashes")
	assert_eq(MapVariation.pick_variant(SEED, 7, 9, 0, 0), 0, "no variants is a safe 0")


func test_it_is_deterministic_and_in_range() -> void:
	for x in range(0, 40):
		for y in range(0, 28):
			var v := MapVariation.pick_variant(SEED, x, y, 0, 4)
			assert_true(v >= 0 and v < 4, "variant stays in [0,4)")
			assert_eq(v, MapVariation.pick_variant(SEED, x, y, 0, 4), "same inputs, same pick")
